# Generated by Django 3.1.2 on 2020-10-09 00:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingName', models.CharField(max_length=100)),
                ('floor', models.IntegerField(default=1)),
                ('roomNumber', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('startTime', models.TimeField(default=datetime.time(4, 0))),
                ('endTime', models.TimeField(default=datetime.time(5, 0))),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModels.location')),
            ],
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataModels.session')),
            ],
        ),
    ]
